services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin123
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped
    mem_limit: 512m

  vault:
    image: vault:1.10.4
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    restart: unless-stopped
    mem_limit: 512m

volumes:
  grafana-storage:
